import type { Metadata } from "next";
import { Silkscreen } from "next/font/google"
import "./globals.css";
import CameraAnimation from "@/components/CameraAnimation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const silkScreen = Silkscreen({
  weight: ["400", "700"],
  display: "swap",
  subsets: ["latin"],
  variable:"--font-silk"
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`max-w-screen overflow-hidden ${silkScreen.variable}`}>
        {children}
      </body>
    </html>
  );
}
